force-app/main/default/objects/LineItem__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LineItem</label>
    <nameField>
        <displayFormat>LIN-{00000}</displayFormat>
        <label>LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineItem__c</fullName>
        <label>LineItem</label>
        <referenceTo>LineItem__c</referenceTo>
        <relationshipLabel>ProductLineItems</relationshipLabel>
        <relationshipName>ProductLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>ProductLineItem</label>
    <nameField>
        <displayFormat>PLI-{00000}</displayFormat>
        <label>ProductLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LineItemTriggerHandler.cls
public class LineItemTriggerHandler {

    public static void insertProductLineItem (List<LineItem__c> items){
        ProductLineItem__c pli = new ProductLineItem__c();
        for(LineItem__c li: items){
 			pli.Description__c = li.Description__C;
            pli.Type__c = li.Type__c;
            pli.LineItem__c = li.Id;
        }
        try {
        	insert pli;    
        }
        catch(Exception ex){
            System.debug(ex);
        }
        
    }
}